### ISSUE TITLE
授業開始時間と終了時間が10分前倒しされてcsvが吐き出される

### ISSUE THREAD

**Issue by hotuta** [prprhyt/cle_analysis#1]
高輪指定、本来1時間目9:20開始のはずが9:10開始、終了も同じように10分前倒しでcsvが吐き出され結果的に10分早いグーグルカレンダーが完成してしまう。

**Comment by hotuta** [comment]
湘南、代々木、高輪を指定のはずが熊本、阿蘇を指定しているような感じになってます。

**Comment by prprhyt** [comment]
この問題はversion0.0.8alphaで解決済みです。報告ありがとうござました。報告を元に修正しました。
